---
abstract: 'Handle bitmasks in an easy and flexible way'
author:
  - 'Klaus Ita'
build_requires:
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Bitmask-Data
no_index:
  directory:
    - inc
    - t
requires:
  Class::Data::Inheritable: 0
  List::Util: 0
  perl: 5.10.0
version: 1.00
